spring:
  application:
    name: "micro-social-net"
  datasource:
      driver-class-name: org.postgresql.Driver
      username: test-user
      password: test-pass
      url: jdbc:postgresql://localhost:5002/test-db
      hikari:
        schema: users_scheme
  jpa:
    database: POSTGRESQL
    show-sql: true
  profiles:
    active: local