version: "3.9"
services:
  postgres:
    image: postgres:16.1-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "test-db"
      POSTGRES_USER: "test-user"
      POSTGRES_PASSWORD: "test-pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d
      - appnetdb-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf:ro
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db-net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.org"
      PGADMIN_DEFAULT_PASSWORD: "pgpass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db-net

volumes:
  appnetdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge